<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit40a5effe36fbe1d7ccb9582f65abc9be
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WpConvertToWebp\\' => 16,
        ),
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WpConvertToWebp\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit40a5effe36fbe1d7ccb9582f65abc9be::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit40a5effe36fbe1d7ccb9582f65abc9be::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit40a5effe36fbe1d7ccb9582f65abc9be::$classMap;

        }, null, ClassLoader::class);
    }
}
